/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knapsack;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author mz-hafizha
 */
public class GUI_FIX extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public GUI_FIX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wt3 = new javax.swing.JTextField();
        val3 = new javax.swing.JTextField();
        wt4 = new javax.swing.JTextField();
        val4 = new javax.swing.JTextField();
        combo_surah2 = new javax.swing.JComboBox<>();
        combo_surah3 = new javax.swing.JComboBox<>();
        combo_surah4 = new javax.swing.JComboBox<>();
        wt1 = new javax.swing.JTextField();
        val1 = new javax.swing.JTextField();
        wt2 = new javax.swing.JTextField();
        val2 = new javax.swing.JTextField();
        combo_surah = new javax.swing.JComboBox<>();
        W = new javax.swing.JTextField();
        bt_cek = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        op1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(wt3);
        wt3.setBounds(420, 240, 60, 30);
        jPanel1.add(val3);
        val3.setBounds(250, 240, 70, 30);
        jPanel1.add(wt4);
        wt4.setBounds(420, 280, 60, 30);
        jPanel1.add(val4);
        val4.setBounds(250, 280, 70, 30);

        combo_surah2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad-Dhuha", "At-Tin", "Al-Insyirah", "Al-Zalzalah", "Al-Adhiyat", "Al-Qori'ah" }));
        combo_surah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_surah2ActionPerformed(evt);
            }
        });
        jPanel1.add(combo_surah2);
        combo_surah2.setBounds(50, 200, 130, 30);

        combo_surah3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad-Dhuha", "At-Tin", "Al-Insyirah", "Al-Zalzalah", "Al-Adhiyat", "Al-Qori'ah" }));
        combo_surah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_surah3ActionPerformed(evt);
            }
        });
        jPanel1.add(combo_surah3);
        combo_surah3.setBounds(50, 240, 130, 30);

        combo_surah4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad-Dhuha", "At-Tin", "Al-Insyirah", "Al-Zalzalah", "Al-Adhiyat", "Al-Qori'ah" }));
        combo_surah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_surah4ActionPerformed(evt);
            }
        });
        jPanel1.add(combo_surah4);
        combo_surah4.setBounds(50, 280, 130, 30);

        wt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wt1ActionPerformed(evt);
            }
        });
        jPanel1.add(wt1);
        wt1.setBounds(420, 160, 60, 30);
        jPanel1.add(val1);
        val1.setBounds(250, 160, 70, 30);
        jPanel1.add(wt2);
        wt2.setBounds(420, 200, 60, 30);

        val2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val2ActionPerformed(evt);
            }
        });
        jPanel1.add(val2);
        val2.setBounds(250, 200, 70, 30);

        combo_surah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad-Dhuha", "At-Tin", "Al-Insyirah", "Al-Zalzalah", "Al-Adhiyat", "Al-Qori'ah" }));
        combo_surah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_surahActionPerformed(evt);
            }
        });
        jPanel1.add(combo_surah);
        combo_surah.setBounds(50, 160, 130, 30);
        jPanel1.add(W);
        W.setBounds(100, 330, 50, 30);

        bt_cek.setText("Cek");
        bt_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cekActionPerformed(evt);
            }
        });
        jPanel1.add(bt_cek);
        bt_cek.setBounds(150, 330, 40, 30);

        hasil.setText("jTextField5");
        jPanel1.add(hasil);
        hasil.setBounds(490, 330, 50, 35);

        op1.setColumns(20);
        op1.setRows(5);
        jScrollPane1.setViewportView(op1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 330, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/mz-hafizha/Pictures/Screenshot from 2020-05-13 17-38-46.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -30, 610, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_surah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_surah2ActionPerformed
        int tin = 162;
        int insyirah = 102;
        int dhuha = 165;
        int zalzalah = 158;
        int adhiyat = 169;
        int qoriah = 160;

        String surah2 = (String) combo_surah2.getSelectedItem();
        if (surah2 == "At-Tin") {
            val2.setText(Integer.toString(tin));
        } else if (surah2 == "Al-Insyirah") {
            val2.setText(Integer.toString(insyirah));
        } else if (surah2 == "Ad-Dhuha") {
            val2.setText(Integer.toString(dhuha));
        } else if (surah2 == "Al-Zalzalah") {
            val2.setText(Integer.toString(zalzalah));
        } else if (surah2 == "Al-Adhiyat") {
            val2.setText(Integer.toString(adhiyat));
        } else {
            val2.setText(Integer.toString(qoriah));
        }
    }//GEN-LAST:event_combo_surah2ActionPerformed

    private void combo_surah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_surah3ActionPerformed
        int tin = 162;
        int insyirah = 102;
        int dhuha = 165;
        int zalzalah = 158;
        int adhiyat = 169;
        int qoriah = 160;

        String surah3 = (String) combo_surah3.getSelectedItem();
        if (surah3 == "At-Tin") {
            val3.setText(Integer.toString(tin));
        } else if (surah3 == "Al-Insyirah") {
            val3.setText(Integer.toString(insyirah));
        } else if (surah3 == "Ad-Dhuha") {
            val3.setText(Integer.toString(dhuha));
        } else if (surah3 == "Al-Zalzalah") {
            val3.setText(Integer.toString(zalzalah));
        } else if (surah3 == "Al-Adhiyat") {
            val3.setText(Integer.toString(adhiyat));
        } else {
            val3.setText(Integer.toString(qoriah));
        }
    }//GEN-LAST:event_combo_surah3ActionPerformed

    private void combo_surah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_surah4ActionPerformed
        int tin = 162;
        int insyirah = 102;
        int dhuha = 165;
        int zalzalah = 158;
        int adhiyat = 169;
        int qoriah = 160;

        String surah4 = (String) combo_surah4.getSelectedItem();
        if (surah4 == "At-Tin") {
            val4.setText(Integer.toString(tin));
        } else if (surah4 == "Al-Insyirah") {
            val4.setText(Integer.toString(insyirah));
        } else if (surah4 == "Ad-Dhuha") {
            val4.setText(Integer.toString(dhuha));
        } else if (surah4 == "Al-Zalzalah") {
            val4.setText(Integer.toString(zalzalah));
        } else if (surah4 == "Al-Adhiyat") {
            val4.setText(Integer.toString(adhiyat));
        } else {
            val4.setText(Integer.toString(qoriah));
        }
    }//GEN-LAST:event_combo_surah4ActionPerformed

    private void wt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wt1ActionPerformed

    }//GEN-LAST:event_wt1ActionPerformed

    private void val2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_val2ActionPerformed

    private void combo_surahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_surahActionPerformed
        int tin = 162;
        int insyirah = 102;
        int dhuha = 165;
        int zalzalah = 158;
        int adhiyat = 169;
        int qoriah = 160;

        String surah1 = (String) combo_surah.getSelectedItem();
        if (surah1 == "At-Tin") {
            val1.setText(Integer.toString(tin));
        } else if (surah1 == "Al-Insyirah") {
            val1.setText(Integer.toString(insyirah));
        } else if (surah1 == "Ad-Dhuha") {
            val1.setText(Integer.toString(dhuha));
        } else if (surah1 == "Al-Zalzalah") {
            val1.setText(Integer.toString(zalzalah));
        } else if (surah1 == "Al-Adhiyat") {
            val1.setText(Integer.toString(adhiyat));
        } else {
            val1.setText(Integer.toString(qoriah));
        }
    }//GEN-LAST:event_combo_surahActionPerformed

    private void bt_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cekActionPerformed
        List<String> surahList = new ArrayList<>();
        
        int w1 = Integer.parseInt(wt1.getText());
        int w2 = Integer.parseInt(wt2.getText());
        int w3 = Integer.parseInt(wt3.getText());
        int w4 = Integer.parseInt(wt4.getText());

        int v1 = Integer.parseInt(val1.getText());
        int v2 = Integer.parseInt(val2.getText());
        int v3 = Integer.parseInt(val3.getText());
        int v4 = Integer.parseInt(val4.getText());

        int cap = Integer.parseInt(W.getText());

        int w[] = new int[]{w1, w2, w3, w4};
        int v[] = new int[]{v1, v2, v3, v4};

        int n = v.length, y;
        int[][] m = new int[n + 1][cap + 1];

        for (int j = 0; j <= cap; j++) {
            if (n <= 0 || cap <= 0) {
                m[0][j] = 0;
            }
            m[0][j] = 0;
        }

        for (int i = 1; i <= n; i++) {
//            System.out.println(">>>>>>>>>>>>>>>>>>>>>>> i: " + i);

            for (int j = 1; j <= cap; j++) {
//                System.out.println(">>>>>>>>>>>>>j: " + j);
//                System.out.println(surahList.size());
                if (w[i - 1] > j) {
                    m[i][j] = m[i - 1][j];
//                    System.out.println("a :::: " + (i - 1) + " " + (j) + " " + m[i][j]);
//                    System.out.println(j - w[i - 1] + " " + v[i - 1]);
                } else {
                    m[i][j] = Math.max(
                            m[i - 1][j],
                            m[i - 1][j - w[i - 1]] + v[i - 1]);
//                    System.out.println("b :::: " + (i - 1) + " " + (j - w[i - 1]) + " " + m[i][j]);
//                    System.out.println(j - w[i - 1] + " " + v[i - 1]);
//                    System.out.println("baru " + (m[i - 1][j - w[i - 1]] + v[i - 1]));
//                    int inj = j - w[i - 1];

                    // kalo maks pada tahap i lebih besar dari i-1
                    if (j == cap && i == n) {
                        int k = cap;
                        for (int x = n; x >= 1; x--) {
//                            System.out.println(k);
                            if (k != 0) {
                                int a = m[x - 1][k]; // tadi
                                int b = m[x - 1][k - w[x - 1]] + v[x - 1];
                                if (a < b) {
//                                    System.out.println("a<b " + a + " " + b + " k " + k);
//                                System.out.println(m[x - 1][j - w[x - 1]]);
                                    System.out.println(v[x - 1]);
                                    if (v[x - 1] == 162) {
                                        surahList.add("At-Tin");                                        
                                    } else if (v[x - 1] == 102){
                                        surahList.add("Al-Insyirah");
                                    } else if (v[x - 1] == 165){
                                        surahList.add("Ad-Dhuha");
                                    } else if (v[x - 1] == 158){
                                        surahList.add("Al-Zalzalah");
                                    } else if (v[x - 1] == 169){
                                        surahList.add("Al-Adhiyat");
                                    } else if (v[x - 1] == 160){
                                        surahList.add("Al-Qori'ah");
                                    }
                                    
                                    k = k - w[x - 1];

                                }
                                // sekarang
//                             System.out.println("ha");
                            } else {
//                                System.out.println("err");
                                break;
                            }
//                            if ((m[x - 1][j - w[x - 1]] + v[x - 1]) > (m[x - 1][j]) && (m[x - 1][j - w[x - 1]] > 0)) {
//                                System.out.println(v[x-1]+" x "+x);
//                            } else {
//                                System.out.println(v[x-2]);
//                            }

                        }

                    }

                }
            }
            int hsl = m[n][cap];
            hasil.setText(Integer.toString(hsl));
            String result = surahList.stream().map(s -> String.valueOf(s)).collect(Collectors.joining(","));
            op1.setText(result);
        }
    }//GEN-LAST:event_bt_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_FIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_FIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_FIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_FIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_FIX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField W;
    private javax.swing.JButton bt_cek;
    private javax.swing.JComboBox<String> combo_surah;
    private javax.swing.JComboBox<String> combo_surah2;
    private javax.swing.JComboBox<String> combo_surah3;
    private javax.swing.JComboBox<String> combo_surah4;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea op1;
    private javax.swing.JTextField val1;
    private javax.swing.JTextField val2;
    private javax.swing.JTextField val3;
    private javax.swing.JTextField val4;
    private javax.swing.JTextField wt1;
    private javax.swing.JTextField wt2;
    private javax.swing.JTextField wt3;
    private javax.swing.JTextField wt4;
    // End of variables declaration//GEN-END:variables
}
